### ISSUE TITLE
Why won't this image display in the page

### ISSUE THREAD

**Issue by hugh1e** [youlgrave-ypres/youlgrave-ypres.github.io#1]

**Comment by hugh1e** [comment]
assets/images/1st-dedication/007 1.jpg

**Comment by Jamstah** [comment]
It does work on the site, just doesn't work in the editor view for some reason: https://www.youlgreave-ypres.org.uk/pages/92%201st-dedication

I would guess its because it has a space in the name, try and avoid spaces!
